version: '3.9'

services:
  pydb:
    container_name: pydb
    image: postgres:latest
    env_file:
      - .env
    ports:
      - 5050:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U theus -d talks"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    volumes:
      - talks:/var/lib/postgresql/data
    
  pymig:
    container_name: pymig
    build: .
    env_file:
      - .env
    command:
      bash -c 'while !</dev/tcp/pydb/5432; do sleep 1; done; python manage.py migrate'
    volumes:
      - .:/code
    depends_on:
      - pydb

  pyapi:
    container_name: pyapi
    build: .
    env_file:
      - .env
    command:
      bash -c 'while !</dev/tcp/pydb/5432; do sleep 1; done; python manage.py runserver 0.0.0.0:8000'
    volumes:
      - .:/code
    stdin_open: true
    tty: true
    ports:
      - 8000:8000
    depends_on:
      - pydb
      - pymig

volumes:
  talks:
    external: true

