databases:
  - name: talks
    databaseName: talks1
    user: theus

services:
  - type: web
    name: talks
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn _project.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: talks
          property: "postgres://theus:OGMmvseVAFjHq07EeSNZCvB9QbH6kpiQ@dpg-cdmr80qen0hm6jqsf9u0-a/talks1"
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
