databases:
  - name: talks
    databaseName: talks1
    user: theus

services:
  - type: web
    name: talks
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn _project.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: talks1
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
