# Generated by Django 4.1.2 on 2022-11-07 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="is_readed",
            field=models.BooleanField(default=False),
        ),
    ]
